import type { Metadata } from "next";
import Link from "next/link";
import { BsCart4 } from "react-icons/bs";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nepali Bazzar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <nav>
      <div className="container mx-auto px-3">
      <ul className="flex justify-around py-2">
        <div className="flex items-center">
        <li className=" p-1 "><Link className='font-[900] text-3xl' href="/">Nepali Bazzar</Link></li>
        <li className="ml-10 p-1 "><Link className=' '  href="/electronics">Electronic</Link></li>
        <li className="ml-10 p-1 "><Link className=' '  href="/men">Men</Link></li>
        <li className="ml-10 p-1 "><Link className=' '  href="/women">Women</Link></li>
        <li className="ml-10 p-1 "><Link className=' '  href="/about">About</Link></li>
        <li className="ml-10 p-1 "><Link className=' '  href="/contact">Contact</Link></li>
        </div>
        <li className=" p-1 "><Link className='font-bold text-2xl text-blue-400'  href="/cart"><BsCart4 /></Link></li>
      </ul>
      </div>
    </nav>
    <main>
      {children}
    </main>
    </body>
    </html>
  );
}
