import type { Metadata } from "next";
import Navbar from "@/app/component/Navbar";
import Footer from "./component/Footer";
import {CartProvider} from "./context/CartContext"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

  export const metadata: Metadata = { 
  title: "Nepali Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          
        <Navbar />
        <main className="mt-16 md:mt-32 lg:mt-20">
          {children}
        </main>
        <footer className="mt-20">
          <Footer />
        </footer>
        </ CartProvider>
      </body>
    </html>
  );
}
